<a href="https://colab.research.google.com/github/smlicciardello-svg/MPM_200_Licciardello/blob/main/Code/assignment_9_database_management.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Packages and Scientific Computing Libraries

"""
Python Packages Overview:
-------------------------
Packages in Python are collections of modules that provide reusable code and functionality.
They allow developers to organize and share complex code libraries that can be easily imported
and used across different projects.

Key Characteristics of Packages:
- Organized hierarchically
- Contain multiple related modules
- Can be installed using package managers like pip
- Extend Python's core functionality

Three Essential Data Science Libraries:
--------------------------------------
1. Pandas (pd):
   - Primary library for data manipulation and analysis
   - Provides DataFrame: a 2D labeled data structure with columns of potentially different types
   - Key Features:
     * Reading/writing data from various sources (CSV, Excel, SQL databases)
     * Data cleaning and preprocessing
     * Complex data transformations
     * Powerful data analysis and aggregation tools

2. NumPy (np):
   - Fundamental package for scientific computing in Python
   - Introduces the ndarray (n-dimensional array) for efficient numerical operations
   - Key Features:
     * High-performance multidimensional array object
     * Mathematical and statistical functions
     * Linear algebra operations
     * Foundation for scientific and numerical computing
     * Enables fast computations on large datasets

3. Matplotlib (plt):
   - Comprehensive library for creating static, animated, and interactive visualizations
   - Provides MATLAB-like plotting interface
   - Key Features:
     * Line plots, scatter plots, bar charts, histograms
     * Customizable plot styles and layouts
     * Support for multiple plot types and graph formats
     * Integration with NumPy for data visualization

Practical Significance:
----------------------
These libraries form the backbone of data science and scientific computing in Python,
enabling complex data analysis, numerical computations, and insightful visualizations
with minimal code.
"""

In [3]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Read the Excel file
df = pd.read_excel("/content/Flavivirus host associations.xlsx")

# Display basic information about the dataset
print(df.info())

# Show the first few rows of the data
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 570 entries, 0 to 569
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sr no.                  570 non-null    int64
 1   Virus                   570 non-null    object
 2   Scientific Name         570 non-null    object
 3   Authors                 570 non-null    object
 4   Year                    430 non-null    object
 5   Title/accession number  570 non-null    object
 6   Journal                 425 non-null    object
 7   Issue                   415 non-null    float64
 8   Volume                  404 non-null    object
 9   Pages                   404 non-null    object
dtypes: float64(1), int64(1), object(8)
memory usage: 44.7+ KB
None

,sr no.,Virus,Scientific Name,Authors,Year,Title/accession number,Journal,Issue,Volume,Pages
0,3,Apoi virus,Rattus rattus,"C. M. Baak-Baak, N. Cigarroa-Toledo, O. M. Tor...",2016,New Records of Ectoparasites Echinolaelaps ech...,Southwestern Entomologist,NaN,NaN,NaN
1,2,Apoi virus,Myodes rufocanus,CDC Arbocat,NaN,CDC Arbocat,NaN,NaN,NaN,NaN
2,0,Apoi virus,Apodemus argenteus,J. S. Mackenzie and D. T. Williams,2009,"The zoonotic flaviviruses of southern, south-e...",Zoonoses Public Health,56.0,6-7,338-56
3,1,Apoi virus,Apodemus speciosus,J. S. Mackenzie and D. T. Williams,2009,"The zoonotic flaviviruses of southern, south-e...",Zoonoses Public Health,56.0,6-7,338-56
4,4,Bagaza virus,Alectoris rufa,"D. Buitrago, A. Rocha, C. Tena-Tomas, M. Vigo,...",2012,Real-time fluorogenic reverse transcription po...,J Vet Diagn Invest,24.0,5,959-63

## Using pandas functions that you have seen in the class address following questions
1. How many entries are there in the dataset?
2. How many viruses are present in the dataset?
3. List those viruses.
4. How many rows of data are present for each virus?
5. How many host species are present in the data?
6. Make a list of host species present.
7. Count the number of unique host species for each virus.
8. Which virus has the most number of hosts?
9. Which host has most number of viruses?

In [8]:
# Count total number of entries in the dataset- 570 entries
df.shape

(570, 10)

In [9]:
# Count unique viruses- 30
df.Virus.nunique()

30

In [10]:
# List of unique viruses
df.Virus.unique().tolist()

['Apoi virus',
 'Bagaza virus',
 'Banzi virus',
 'Bouboui virus',
 'Bussuquara virus',
 'Cacipacore virus',
 'Dakar bat virus',
 'Dengue virus',
 'Entebbe bat virus',
 'Iguape virus',
 'Ilheus virus',
 'Japanese encephalitis virus',
 'Koutango virus',
 'Kunjin virus',
 'Kyasanur forest virus',
 'Louping-ill virus',
 'Modoc virus',
 'Murray Valley encephalitis virus',
 'Omsk hemorrhagic fever virus',
 'Rio Bravo virus',
 'Rocio virus',
 'St. Louis Encephalitis virus',
 'Tembusu virus',
 'Tickborne encephalitis virus',
 'Uganda S virus',
 'Usutu virus',
 'Wesselsbron virus',
 'West Nile virus',
 'Yellow fever virus',
 'Zika virus']

In [11]:
# Count of each unique virus
df.groupby('Virus').agg({'sr no.' : 'count'})

                                  sr no.
Virus
Apoi virus                             4
Bagaza virus                           2
Banzi virus                            2
Bouboui virus                          1
Bussuquara virus                       3
Cacipacore virus                       1
Dakar bat virus                        5
Dengue virus                          27
Entebbe bat virus                      6
Iguape virus                           1
Ilheus virus                           5
Japanese encephalitis virus           25
Koutango virus                         1
Kunjin virus                           3
Kyasanur forest virus                  6
Louping-ill virus                     13
Modoc virus                            3
Murray Valley encephalitis virus       3
Omsk hemorrhagic fever virus           3
Rio Bravo virus                        9
Rocio virus                            2
St. Louis Encephalitis virus          72
Tembusu virus                          2
Tickborne encephalitis virus          84
Uganda S virus                         7
Usutu virus                           65
Wesselsbron virus                      3
West Nile virus                      194
Yellow fever virus                    11
Zika virus                             7

In [12]:
# Count unique host species
df['Scientific Name'].nunique()

419

In [13]:
# List of unique host species
df['Scientific Name'].unique().tolist()

['Rattus rattus',
 'Myodes rufocanus',
 'Apodemus argenteus',
 'Apodemus speciosus',
 'Alectoris rufa',
 'Phasianus colchicus',
 'Mastomys natalensis',
 'Mesocricetus auratus',
 'Papio papio',
 'Equus caballus',
 'Alouatta belzebul',
 'Proechimys guyannensis',
 'Chaerephon pumilus',
 'Taphozous perforatus',
 'Mops condylurus',
 'Scotophilus nigrita',
 'Otomops sp',
 'Carollia brevicauda',
 'Molossus molossus',
 'Myotis nigricans',
 'Natalus stramineus',
 'Rousettus leschenaultii',
 'Artibeus planirostris',
 'Caluromys philander',
 'Carollia perspicillata',
 'Didelphis marsupialis',
 'Hylaeamys megacephalus',
 'Marmosa demerarae',
 'Marmosa murina',
 'Marmosops parvidens',
 'Mesomys hispidus',
 'Oecomys sp',
 'Philander opossum',
 'Proechimys cuvieri',
 'Zygodontomys brevicauda',
 'Artibeus jamaicensis',
 'Artibeus lituratus',
 'Glossophaga soricina',
 'Artibeus sp',
 'Uroderma sp',
 'Macaca nemestrina',
 'Mus musculus',
 'Eidolon helvum',
 'Pipistrellus pipistrellus',
 'Rhinolophus sp',
 'Rousettus spinalatus',
 'Macaca mulatta',
 'Equus ferus',
 'Molothrus bonariensis',
 'Sporophila caerulescens',
 'Hipposideros armiger',
 'Rhinolophus pusillus',
 'Vespertilio sinensis',
 'Bos taurus',
 'Bos gaurus',
 'Crocidura macowi',
 'Turdus merula',
 'Turdus iliacus',
 'Sturnus vulgaris',
 'Turdus philomelos',
 'Columba livia',
 'Sus scrofa',
 'Alouatta pigra',
 'Sus domesticus',
 'Myotis pilosus',
 'Scotophilus kuhlii',
 'Rhinolophus affinis',
 'Miniopterus schreibersii',
 'Ovis aries',
 'Murina aurata',
 'Padda oryzivora',
 'Spilopelia chinensis',
 'Gallus gallus',
 'Oriolus flavocinctus',
 'Pteropus sp',
 'Vandeleuria oleracea',
 'Macaca radiata',
 'Madromys blanfordi',
 'Semnopithecus entellus',
 'Capra aegagrus',
 'Capra hircus',
 'Apodemus sylvaticus',
 'Canis lupus',
 'Capreolus capreolus',
 'Cervus elaphus',
 'Lagopus lagopus',
 'Lepus timidus',
 'Sorex araneus',
 'Peromyscus maniculatus',
 'Egretta novaehollandiae',
 'Microtus gregalis',
 'Ondatra zibethicus',
 'Microtus oeconomus',
 'Molossus rufus',
 'Tadarida brasiliensis',
 'Eptesicus fuscus',
 'Desmodus rotundus',
 'Sturnira lilium',
 'Zonotrichia capensis',
 'Agelaioides badius',
 'Agelaius phoeniceus',
 'Alouatta sp',
 'Ateles paniscus',
 'Bradypus variegatus',
 'Bubo virginianus',
 'Buteogallus coronatus',
 'Butorides striata',
 'Callipepla gambelii',
 'Calomys musculinus',
 'Campylorhynchus brunneicapillus',
 'Caracara cheriway',
 'Carpodacus mexicanus',
 'Charadrius vociferus',
 'Choloepus hoffmanni',
 'Colaptes melanochloros',
 'Columbina passerina',
 'Columbina picui',
 'Conopophaga aurita',
 'Dendroica coronata',
 'Egretta thula',
 'Elaenia albiceps',
 'Falco sparverius',
 'Furnarius rufus',
 'Geothlypis trichas',
 'Geotrygon montana',
 'Hypocnemis cantator',
 'Icterus bullockii',
 'Ixobrychus exilis',
 'Lanius ludovicianus',
 'Lepus californicus',
 'Lophospingus pusillus',
 'Melospiza melodia',
 'Melozone aberti',
 'Mimus polyglottos',
 'Molothrus ater',
 'Myiobius barbatus',
 'Myrmotherula hauxwelli',
 'Nycticorax nycticorax',
 'Oligoryzomys nigripes',
 'Orcinus orca',
 'Passer domesticus',
 'Phalcoboenus chimango',
 'Philydor erythrocercum',
 'Pitangus sulphuratus',
 'Poospiza nigrorufa',
 'Porzana carolina',
 'Procyon lotor',
 'Pseudoseisura lophotes',
 'Pyrocephalus rubinus',
 'Saltator maximus',
 'Sapajus apella',
 'Sayornis nigricans',
 'Stelgidopteryx serripennis',
 'Toxostoma redivivum',
 'Turdus amaurochalinus',
 'Vermivora ruficapilla',
 'Zenaida asiatica',
 'Zenaida auriculata',
 'Zenaida macroura',
 'Tadorna sp',
 'Anas platyrhynchos',
 'Apodemus agrarius',
 'Myodes rutilus',
 'Alticola argentatus',
 'Apodemus pallipes',
 'Microtus ilaeus',
 'Bison bonasus',
 'Macaca sylvanus',
 'Apodemus flavicollis',
 'Microtus agrestis',
 'Microtus arvalis',
 'Apodemus sp',
 'Myodes glareolus',
 'Lagomorpha sp',
 'Sciuridae sp',
 'Acrocephalus dumetorum',
 'Anas crecca',
 'Bombycilla garrulus',
 'Carduelis carduelis',
 'Carduelis chloris',
 'Carduelis spinus',
 'Carpodacus erythrinus',
 'Dendrocopos major',
 'Emberiza citrinella',
 'Ficedula hypoleuca',
 'Luscinia calliope',
 'Luscinia luscinia',
 'Mergus merganser',
 'Parus ater',
 'Parus major',
 'Parus montanus',
 'Passer montanus',
 'Phoenicurus phoenicurus',
 'Phylloscopus collybita',
 'Phylloscopus proregulus',
 'Phylloscopus trochilus',
 'Pyrrhula pyrrhula',
 'Riparia riparia',
 'Sitta europaea',
 'Spatula clypeata',
 'Sylvia curruca',
 'Vanellus vanellus',
 'Ovis orientalis',
 'Accipiter gentilis',
 'Anthus trivialis',
 'Bonasa bonasia',
 'Carduelis flammea',
 'Clangula hyemalis',
 'Corvus corone',
 'Corvus monedula',
 'Crex crex',
 'Emberiza fucata',
 'Fringilla coelebs',
 'Fringilla montifringilla',
 'Fulica atra',
 'Jynx torquilla',
 'Lanius collurio',
 'Lanius cristatus',
 'Loxia curvirostra',
 'Melanitta fusca',
 'Motacilla alba',
 'Motacilla flava',
 'Pica pica',
 'Scolopax rusticola',
 'Spatula querquedula',
 'Troglodytes troglodytes',
 'Turdus pallidus',
 'Turdus pilaris',
 'Turdus ruficollis',
 'Arvicanthis niloticus',
 'Cricetomys gambianus',
 'Saxicola rubetra',
 'Andropadus virens',
 'Bycanistes sharpii',
 'Praomys sp',
 'Turdus libonyanus',
 'Aegolius funereus',
 'Erithacus rubecula',
 'Glaucidium passerinum',
 'Surnia ulula',
 'Hirundo rustica',
 'Parus caeruleus',
 'Strix nebulosa',
 'Ardea cinerea',
 'Clanga clanga',
 'Larus michahellis',
 'Merops apiaster',
 'Picus viridis',
 'Streptopelia decaocto',
 'Garrulus glandarius',
 'Ciconia ciconia',
 'Pandion haliaetus',
 'Equus asinus',
 'Acrocephalus scirpaceus',
 'Bubo bubo',
 'Circus aeruginosus',
 'Delichon urbicum',
 'Emberiza schoeniclus',
 'Falco tinnunculus',
 'Gypaetus barbatus',
 'Pavo cristatus',
 'Phoenicurus ochruros',
 'Strix aluco',
 'Strix uralensis',
 'Sylvia atricapilla',
 'Sylvia borin',
 'Sylvia communis',
 'Tyto alba',
 'Alcedo atthis',
 'Larosterna inca',
 'Serinus canaria',
 'Turdus sp',
 'Asio otus',
 'Caprimulgus europaeus',
 'Larus ridibundus',
 'Desmodillus auricularis',
 'Acrocephalus schoenobaenus',
 'Anthus pratensis',
 'Meleagris gallopavo',
 'Prunella modularis',
 'Dendroica petechia',
 'Icterus leucopteryx',
 'Leptotila jamaicensis',
 'Mniotilta varia',
 'Myiopagis cotta',
 'Parkesia noveboracensis',
 'Tiaris bicolor',
 'Turdus aurantius',
 'Turdus jamaicensis',
 'Tyrannus caudifasciatus',
 'Vireo modestus',
 'Anorrhinus tickelli',
 'Larus leucophthalmus',
 'Anser anser domesticus ',
 'Platycercus sp',
 'Branta canadensis',
 'Mephitis mephitis',
 'Bonasa umbellus',
 'Ciconia sp',
 'Canis familiaris',
 'Sciurus carolinensis',
 'Cyanocitta cristata',
 'Corvus brachyrhynchos',
 'Gallus domesticus',
 'Bubulcus ibis',
 'Aegypius monachus',
 'Corvus frugilegus',
 'Coracornis raveni',
 'Cardinalis cardinalis',
 'Fulica americana',
 'Phalacrocorax sp',
 'Dumetella carolinensis',
 'Falco columbarius',
 'Falco punctatus',
 'Accipiter nisus',
 'Aquila adalberti',
 'Quiscalus quiscula',
 'Rodent sp',
 'Aquila fasciata',
 'Pelophylax ridibundus',
 'Aquila chrysaetos',
 'Sciurus niger',
 'Athene noctua',
 'Chaerephon bregullae',
 'Anaxyrus fowleri',
 'Parus atricapillus',
 'Arabitragus jayakari',
 'Corvus corax',
 'Crocodylus moreletii',
 'Panurus biarmicus',
 'Haliaeetus albicilla',
 'Hylocichla mustelina',
 'Toxostoma rufum',
 'Parus carolinensis',
 'Loriini sp',
 'Capra falconeri',
 'Pelecanus conspicillatus',
 'Quiscalus major',
 'Gymnogyps californianus',
 'Asio flammeus',
 'Coragyps atratus',
 'Buteo swainsoni',
 'Pelecanus occidentalis',
 'Cygnus buccinator',
 'Sternula albifrons',
 'Ictinia mississippiensis',
 'Phalacrocorax auritus',
 'Buteo regalis',
 'Calidris alba',
 'Sturnidae',
 'Charadrius melodus',
 'Haliaeetus leucocephalus',
 'Akodon mimus',
 'Accipitridae sp',
 'Larus smithsonianus',
 'Actitis macularius',
 'Sternula antillarum',
 'Pelecanus erythrorhynchos',
 'Phoenicopterus ruber',
 'Anatidae sp',
 'Nestor notabilis',
 'Camelus dromedarius',
 'Larus delawarensis',
 'Colaptes auratus',
 'Baeolophus bicolor',
 'Corvus ossifragus',
 'Accipiter striatus',
 'Carduelis tristis',
 'Turdus migratorius',
 'Anisognathus somptuosus',
 'Campylorhamphus trochilirostris',
 'Coereba flaveola',
 'Elaenia flavogaster',
 'Thraupis palmarum',
 'Turdus leucomelas',
 'Odocoileus virginianus',
 'Oreamnos americanus',
 'Rangifer tarandus',
 'Ursus maritimus',
 'Struthio camelus',
 'Accipiter cooperii',
 'Agelaius tricolor',
 'Aphelocoma californica',
 'Ardea alba',
 'Ardea herodias',
 'Buteo jamaicensis',
 'Buteo lineatus',
 'Callipepla californica',
 'Cistothorus palustris',
 'Dryobates nuttallii',
 'Euphagus cyanocephalus',
 'Falco peregrinus',
 'Geococcyx californianus',
 'Lonchura punctulata',
 'Melospiza lincolnii',
 'Melozone crissalis',
 'Myiarchus cinerascens',
 'Pheucticus melanocephalus',
 'Pica nuttalli',
 'Tachycineta bicolor',
 'Thryomanes bewickii',
 'Tyrannus verticalis',
 'Zonotrichia atricapilla',
 'Zonotrichia leucophrys',
 'Acrocephalus palustris',
 'Locustella luscinioides',
 'Saguinus geoffroyi',
 'Primate sp',
 'Erythrocebus patas',
 'Alouatta caraya',
 'Alouatta guariba',
 'Chlorocebus aethiops',
 'Alouatta sara',
 'Colobus guereza',
 'Aotus sp',
 'Callithrix jacchus',
 'Macaca fascicularis',
 'Pongo pygmaeus',
 'Sapajus libidinosus']

In [14]:
# Count of host species for each virus
virus_host_count=df.groupby('Virus').agg({'Scientific Name' : 'count'})
virus_host_count

                                  Scientific Name
Virus
Apoi virus                                      4
Bagaza virus                                    2
Banzi virus                                     2
Bouboui virus                                   1
Bussuquara virus                                3
Cacipacore virus                                1
Dakar bat virus                                 5
Dengue virus                                   27
Entebbe bat virus                               6
Iguape virus                                    1
Ilheus virus                                    5
Japanese encephalitis virus                    25
Koutango virus                                  1
Kunjin virus                                    3
Kyasanur forest virus                           6
Louping-ill virus                              13
Modoc virus                                     3
Murray Valley encephalitis virus                3
Omsk hemorrhagic fever virus                    3
Rio Bravo virus                                 9
Rocio virus                                     2
St. Louis Encephalitis virus                   72
Tembusu virus                                   2
Tickborne encephalitis virus                   84
Uganda S virus                                  7
Usutu virus                                    65
Wesselsbron virus                               3
West Nile virus                               194
Yellow fever virus                             11
Zika virus                                      7

In [5]:
# Most diverse viruses (viruses with most unique host species)
virus_host_count.nlargest(5, "Scientific Name")

                              Scientific Name
Virus
West Nile virus                           194
Tickborne encephalitis virus               84
St. Louis Encephalitis virus               72
Usutu virus                                65
Dengue virus                               27

# Metadata

## Given that we are interested in the metadata associated with these host species, we will import datasets associated with the metadata for both bird and mammalian species.

1. Birds

In [15]:
birds_meta = pd.read_excel('/content/Handbook of the Birds of the World and BirdLife International Digital Checklist of the Birds of the World_Version_9.xlsx')
birds_meta

,Seq.,Subsp. Seq.,Order,Family name,Family,Subfamily,Tribe,Common name,Scientific name,Authority,2024 IUCN Red List category,Synonyms,Alternative common names,Taxonomic source(s),SISRecID,SpcRecID\n(used before SISRecID),SubsppID
0,1.0,0.0,STRUTHIONIFORMES,Struthionidae,Ostriches,NaN,NaN,Common Ostrich,Struthio camelus,"Linnaeus, 1758",LC,NaN,NaN,"del Hoyo, J., Collar, N.J., Christie, D.A., El...",45020636.0,1016860.0,NaN
1,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Struthio camelus syriacus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45020636_1
2,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,Struthio camelus camelus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45020636_2
3,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,Struthio camelus massaicus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45020636_3
4,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,Struthio camelus australis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45020636_4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33260,102032.0,NaN,PASSERIFORMES,Thraupidae,Tanagers,Thraupinae,NaN,NaN,Tangara cyanoptera,"(Swainson, 1834)",NR,NaN,NaN,"SACC (2005 & updates); Sibley & Monroe (1990, ...",22722950.0,9428.0,NaN
33261,102033.0,NaN,PASSERIFORMES,Thraupidae,Tanagers,Thraupinae,NaN,NaN,Tangara vassorii,"(Boissonneau, 1840)",NR,NaN,NaN,"SACC (2005 & updates); Sibley & Monroe (1990, ...",22722933.0,9423.0,NaN
33262,102034.0,NaN,PASSERIFORMES,Thraupidae,Tanagers,Thraupinae,NaN,NaN,Tangara velia,"(Linnaeus, 1758)",NR,NaN,NaN,"SACC (2005 & updates); Sibley & Monroe (1990, ...",22731274.0,31308.0,NaN
33263,102035.0,NaN,PASSERIFORMES,Thraupidae,Tanagers,Thraupinae,NaN,NaN,Tangara brasiliensis,"(Linnaeus, 1766)",NR,NaN,NaN,Stotz et al. (1996),22731781.0,31402.0,NaN
33264,102036.0,NaN,PASSERIFORMES,Thraupidae,Tanagers,Thraupinae,NaN,NaN,Tangara cucullata,"(Swainson, 1834)",NR,NaN,NaN,AOU (1998 & supplements); Sibley & Monroe (199...,22722887.0,9408.0,NaN

The data for birds is at subspecies level. It means that there is species name represented by column `Seq.`. All rows in same number represent one species.

2. Mammals

## Similarly, read file for mammals metadata.

In [16]:
loc='/content/IUCN Mammals, Birds, Reptiles, and Amphibians.csv'
mammals_meta = pd.read_csv(loc, encoding='latin-1')
mammals_meta.head()

,Species ID,Kingdom,Phylum,Class,Order,Family,Genus,Species,Authority,Infraspecific rank,...,Synonyms,Common names (Eng),Common names (Fre),Common names (Spa),Red List status,Red List criteria,Red List criteria version,Year assessed,Population trend,Petitioned
0,42641.0,ANIMALIA,CHORDATA,MAMMALIA,RODENTIA,MURIDAE,Abditomys,latidens,"(Sanborn, 1952)",NaN,...,NaN,Luzon Broad-toothed Rat,NaN,NaN,DD,NaN,3.1,2008.0,unknown,N
1,22687170.0,ANIMALIA,CHORDATA,AVES,CAPRIMULGIFORMES,TROCHILIDAE,Abeillia,abeillei,"(Lesson & DeLattre, 1839)",NaN,...,NaN,Emerald-chinned Hummingbird,NaN,NaN,LC,NaN,3.1,2012.0,decreasing,N
2,17879.0,ANIMALIA,CHORDATA,MAMMALIA,RODENTIA,MURIDAE,Abeomelomys,sevia,"(Tate & Archbold, 1935)",NaN,...,Melomys sevia|Pogonomelomys sevia,"Menzies' Mouse, Menzies's Mouse, Highland Brus...",NaN,NaN,LC,NaN,3.1,2016.0,unknown,N
3,47760825.0,ANIMALIA,CHORDATA,MAMMALIA,RODENTIA,CRICETIDAE,Abrawayaomys,ruschii,"Cunha & Cruz, 1979",NaN,...,NaN,Ruschi's Rat,NaN,NaN,LC,NaN,3.1,2016.0,unknown,N
4,42656.0,ANIMALIA,CHORDATA,MAMMALIA,RODENTIA,ABROCOMIDAE,Abrocoma,bennettii,"Waterhouse, 1837",NaN,...,NaN,Bennett's Chinchilla Rat,NaN,NaN,LC,NaN,3.1,2016.0,unknown,N

## For both birds and mammals answer the following questions.
1. Size of the datasets
2. For birds, filter the dataset using species-level rows only. Hint. Column `Subsp. Seq.` value of 0 indicates the main species name
3. How many bird species and mammal species are present in data frames?

Bird Data

In [34]:
# 1. Size
birds_meta.shape

(33265, 17)

In [35]:
# 2. Filter using the species-level rows
Species_level_only_birds= birds_meta[birds_meta['Subsp. Seq.'] == 0]
Species_level_only_birds
Bird_filter=Species_level_only_birds.groupby('Scientific name')
Bird_filter

In [36]:
#3. How many bird species are present
Species_level_only_birds['Scientific name'].nunique()

11198

Mammal Dataset

In [22]:
# 1. Size
mammals_meta.shape

(16081, 23)

In [23]:
# 2. Filter using the species-level rows
mammal_filter=mammals_meta.groupby('Species')
mammal_filter

In [24]:
#3. How many mammal species are present
mammals_meta.Species.nunique()

8779

# Database Integration Exercise
The main objective of this exercise is to create a comprehensive database by combining three data frames. Follow these steps  n your analysis.

## Create a concept map:  
* Illustrate the relationships between the three data frames.  
* Identify and highlight the Primary Keys in each data frame.  
* Use a diagramming tool (e.g., PowerPoint, LucidChart, or Draw.io) to create a visual representation of these connections.  
* Pay special attention to how you plan to merge the Mammals and Birds data frames.

In [ ]:
Added in models folder

## Perform a vertical join of Mammals and Birds data frames:  
* Identify and select only the common columns present in both data frames.  
* Use `pd.concat()` or `df.append()` to create a larger dataframe called **metadata**.  
* Ensure the resulting dataframe has the correct number of rows and columns.

In [96]:
#rename bird columns
Species_level_only_birds = Species_level_only_birds.rename(columns={'SISRecID': 'Species ID', '2024 IUCN Red List category': 'Red List status'})

#add bird class
Species_level_only_birds['Class'] = 'AVES'

#create scientific name column
mammals_meta['Scientific name']= mammals_meta['Genus'] + ' ' + mammals_meta['Species']

#rename mammal columns
mammals_meta = mammals_meta.rename(columns={'Family': 'Family name', 'Common names (Eng)': 'Common name',})

In [97]:
#merge spreadsheets
metadata_all_columns=pd.concat([Species_level_only_birds, mammals_meta], axis=0, ignore_index=True)
metadata_all_columns

,Seq.,Subsp. Seq.,Order,Family name,Family,Subfamily,Tribe,Common name,Scientific name,Authority,...,Infraspecific name,Infraspecific authority,Stock/subpopulation,Common names (Fre),Common names (Spa),Red List criteria,Red List criteria version,Year assessed,Population trend,Petitioned
0,1.0,0.0,STRUTHIONIFORMES,Struthionidae,Ostriches,NaN,NaN,Common Ostrich,Struthio camelus,"Linnaeus, 1758",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,0.0,STRUTHIONIFORMES,Struthionidae,Ostriches,NaN,NaN,Somali Ostrich,Struthio molybdophanes,"Reichenow, 1883",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,0.0,STRUTHIONIFORMES,Rheidae,Rheas,NaN,NaN,Greater Rhea,Rhea americana,"(Linnaeus, 1758)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,0.0,STRUTHIONIFORMES,Rheidae,Rheas,NaN,NaN,Lesser Rhea,Rhea pennata,"d'Orbigny, 1834",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,0.0,STRUTHIONIFORMES,Tinamidae,Tinamous,NaN,NaN,Tawny-breasted Tinamou,Nothocercus julius,"(Bonaparte, 1854)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27280,NaN,NaN,CETARTIODACTYLA,CAMELIDAE,NaN,NaN,NaN,NaN,Vicugna pacos,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27281,NaN,NaN,PASSERIFORMES,STURNIDAE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27282,NaN,NaN,RODENTIA,MURIDAE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27283,NaN,NaN,CETARTIODACTYLA,SUIDAE,NaN,NaN,NaN,NaN,Sus scrofa domesticus,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27284,NaN,NaN,RODENTIA,MURIDAE,NaN,NaN,NaN,NaN,Hylomyscus pamfi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
#select only overlapping columns and rename
metadata= metadata_all_columns[['Species ID','Class', 'Order', 'Family name', 'Common name', 'Scientific name', 'Authority', 'Synonyms', 'Red List status']]
metadata

,Species ID,Class,Order,Family name,Common name,Scientific name,Authority,Synonyms,Red List status
0,45020636.0,AVES,STRUTHIONIFORMES,Struthionidae,Common Ostrich,Struthio camelus,"Linnaeus, 1758",NaN,LC
1,22732795.0,AVES,STRUTHIONIFORMES,Struthionidae,Somali Ostrich,Struthio molybdophanes,"Reichenow, 1883",NaN,VU
2,22678073.0,AVES,STRUTHIONIFORMES,Rheidae,Greater Rhea,Rhea americana,"(Linnaeus, 1758)",NaN,NT
3,22678081.0,AVES,STRUTHIONIFORMES,Rheidae,Lesser Rhea,Rhea pennata,"d'Orbigny, 1834",NaN,LC
4,22678157.0,AVES,STRUTHIONIFORMES,Tinamidae,Tawny-breasted Tinamou,Nothocercus julius,"(Bonaparte, 1854)",NaN,LC
...,...,...,...,...,...,...,...,...,...
27280,NaN,MAMMALIA,CETARTIODACTYLA,CAMELIDAE,NaN,Vicugna pacos,NaN,NaN,NaN
27281,NaN,AVES,PASSERIFORMES,STURNIDAE,NaN,NaN,NaN,NaN,NaN
27282,NaN,MAMMALIA,RODENTIA,MURIDAE,NaN,NaN,NaN,NaN,NaN
27283,NaN,MAMMALIA,CETARTIODACTYLA,SUIDAE,NaN,Sus scrofa domesticus,NaN,NaN,NaN
27284,972559.0,MAMMALIA,RODENTIA,MURIDAE,NaN,Hylomyscus pamfi,NaN,NaN,NaN

In [100]:
#check that merge was done correctly
metadata.shape

(27285, 9)

## Merge the metadata dataframe with the Flavivirus dataframe:  
* Experiment with different join types: `inner`, `outer`, `left`, and `right`.  
* For each join type, record the resulting dataframe's shape (rows and columns).  
* Determine the **theoretically correct size of the merged dataframe if done manually**.  
* Compare the results of each join type with the expected outcome.  
* Choose the most appropriate join type based on your analysis.

In [114]:
#rename and inner merge
metadata=metadata.rename(columns={'Scientific name' : 'Scientific Name'})
merged_df_inner=pd.merge(df, metadata, on='Scientific Name', how='inner')
merged_df_inner

,sr no.,Virus,Scientific Name,Authors,Year,Title/accession number,Journal,Issue,Volume,Pages,Species ID,Class,Order,Family name,Common name,Authority,Synonyms,Red List status
0,3,Apoi virus,Rattus rattus,"C. M. Baak-Baak, N. Cigarroa-Toledo, O. M. Tor...",2016,New Records of Ectoparasites Echinolaelaps ech...,Southwestern Entomologist,NaN,NaN,NaN,19360.0,MAMMALIA,RODENTIA,MURIDAE,"House Rat, Ship Rat, Roof Rat, Black Rat","(Linnaeus, 1758)",NaN,LC
1,2,Apoi virus,Myodes rufocanus,CDC Arbocat,NaN,CDC Arbocat,NaN,NaN,NaN,NaN,4974.0,MAMMALIA,RODENTIA,CRICETIDAE,"Grey Red-backed Vole, Grey-sided Vole, Gray Re...","(Sundevall, 1846)",Clethrionomys rufocanus |Clethrionomys sikota...,LC
2,0,Apoi virus,Apodemus argenteus,J. S. Mackenzie and D. T. Williams,2009,"The zoonotic flaviviruses of southern, south-e...",Zoonoses Public Health,56.0,6-7,338-56,42642.0,MAMMALIA,RODENTIA,MURIDAE,Small Japanese Field Mouse,"(Temminck, 1844)",NaN,LC
3,1,Apoi virus,Apodemus speciosus,J. S. Mackenzie and D. T. Williams,2009,"The zoonotic flaviviruses of southern, south-e...",Zoonoses Public Health,56.0,6-7,338-56,1903.0,MAMMALIA,RODENTIA,MURIDAE,Large Japanese Field Mouse,"(Temminck, 1844)",Micromys speciosus subspecies ainu,LC
4,4,Bagaza virus,Alectoris rufa,"D. Buitrago, A. Rocha, C. Tena-Tomas, M. Vigo,...",2012,Real-time fluorogenic reverse transcription po...,J Vet Diagn Invest,24.0,5,959-63,22678711.0,AVES,GALLIFORMES,Phasianidae,Red-legged Partridge,"(Linnaeus, 1758)",NaN,NT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
867,561,Zika virus,Callithrix jacchus,"C. Akoua-Koffi, K. D. Ekra, A. B. Kone, N. S. ...",2002,[Detection and management of the yellow fever ...,Med Trop (Mars),62.0,3,305-9,41518.0,MAMMALIA,PRIMATES,CALLITRICHIDAE,"Common Marmoset, White-tufted-ear Marmoset","(Linnaeus, 1758)",NaN,LC
868,565,Zika virus,Macaca mulatta,E. B. Hayes,2009,Zika virus outside Africa,Emerg Infect Dis,15.0,9,1347-50,12554.0,MAMMALIA,PRIMATES,CERCOPITHECIDAE,"Rhesus Monkey, Rhesus Macaque","(Zimmermann, 1780)",Macaca brachyurus |Macaca brevicaudatus |Mac...,LC
869,564,Zika virus,Macaca fascicularis,"G. H. Leung, R. W. Baird, J. Druce and N. M. A...",2015,Zika Virus Infection in Australia Following a ...,Southeast Asian J Trop Med Public Health,46.0,3,460-4,12551.0,MAMMALIA,PRIMATES,CERCOPITHECIDAE,"Nicobar Crab-eating Macaque, Nicobar Cynomolgu...","(Raffles, 1821)",NaN,LC
870,566,Zika virus,Pongo pygmaeus,"N. D. Wolfe, A. M. Kilbourn, W. B. Karesh, H. ...",2001,Sylvatic transmission of arboviruses among Bor...,American Journal of Tropical Medicine and Hygiene,64.0,5-6,310-316,17975.0,MAMMALIA,PRIMATES,HOMINIDAE,Bornean Orangutan,"(Linnaeus, 1760)",Simia pygmaeus,CR
871,567,Zika virus,Sapajus libidinosus,"S. Favoretto, D. Araujo, D. Oliveira, N. Duart...",2016,First detection of Zika virus in neotropical p...,bioRxiv,NaN,NaN,49395,136346.0,MAMMALIA,PRIMATES,CEBIDAE,"Bearded Capuchin, Black-striped Capuchin","(Spix, 1823)",Cebus libidinosus,LC

In [115]:
merged_df_inner.shape

(872, 18)

In [116]:
#outer merge
merged_df_outer=pd.merge(df, metadata, on='Scientific Name', how='outer')
merged_df_outer

,sr no.,Virus,Scientific Name,Authors,Year,Title/accession number,Journal,Issue,Volume,Pages,Species ID,Class,Order,Family name,Common name,Authority,Synonyms,Red List status
0,NaN,NaN,Abditomys latidens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42641.0,MAMMALIA,RODENTIA,MURIDAE,Luzon Broad-toothed Rat,"(Sanborn, 1952)",NaN,DD
1,NaN,NaN,Abeillia abeillei,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22687170.0,AVES,CAPRIMULGIFORMES,Trochilidae,Emerald-chinned Hummingbird,"(Lesson & DeLattre, 1839)",NaN,LC
2,NaN,NaN,Abeillia abeillei,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22687170.0,AVES,CAPRIMULGIFORMES,TROCHILIDAE,Emerald-chinned Hummingbird,"(Lesson & DeLattre, 1839)",NaN,LC
3,NaN,NaN,Abeomelomys sevia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17879.0,MAMMALIA,RODENTIA,MURIDAE,"Menzies' Mouse, Menzies's Mouse, Highland Brus...","(Tate & Archbold, 1935)",Melomys sevia|Pogonomelomys sevia,LC
4,NaN,NaN,Abrawayaomys ruschii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47760825.0,MAMMALIA,RODENTIA,CRICETIDAE,Ruschi's Rat,"Cunha & Cruz, 1979",NaN,LC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27509,NaN,NaN,chiroptera sp.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MAMMALIA,CHIROPTERA,PHYLLOSTOMIDAE,NaN,NaN,NaN,NaN
27510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MAMMALIA,RODENTIA,MURIDAE,NaN,NaN,NaN,NaN
27511,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AVES,PASSERIFORMES,STURNIDAE,NaN,NaN,NaN,NaN
27512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AVES,PASSERIFORMES,STURNIDAE,NaN,NaN,NaN,NaN
27513,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MAMMALIA,RODENTIA,MURIDAE,NaN,NaN,NaN,NaN

In [117]:
merged_df_outer.shape

(27514, 18)

In [112]:
#left merge
merged_df_left=pd.merge(df, metadata, on='Scientific Name', how='left')
merged_df_left=merged_df_left.drop_duplicates(subset='sr no.', keep='first')
merged_df_left

,sr no.,Virus,Scientific Name,Authors,Year,Title/accession number,Journal,Issue,Volume,Pages,Species ID,Class,Order,Family name,Common name,Authority,Synonyms,Red List status
0,3,Apoi virus,Rattus rattus,"C. M. Baak-Baak, N. Cigarroa-Toledo, O. M. Tor...",2016,New Records of Ectoparasites Echinolaelaps ech...,Southwestern Entomologist,NaN,NaN,NaN,19360.0,MAMMALIA,RODENTIA,MURIDAE,"House Rat, Ship Rat, Roof Rat, Black Rat","(Linnaeus, 1758)",NaN,LC
1,2,Apoi virus,Myodes rufocanus,CDC Arbocat,NaN,CDC Arbocat,NaN,NaN,NaN,NaN,4974.0,MAMMALIA,RODENTIA,CRICETIDAE,"Grey Red-backed Vole, Grey-sided Vole, Gray Re...","(Sundevall, 1846)",Clethrionomys rufocanus |Clethrionomys sikota...,LC
2,0,Apoi virus,Apodemus argenteus,J. S. Mackenzie and D. T. Williams,2009,"The zoonotic flaviviruses of southern, south-e...",Zoonoses Public Health,56.0,6-7,338-56,42642.0,MAMMALIA,RODENTIA,MURIDAE,Small Japanese Field Mouse,"(Temminck, 1844)",NaN,LC
3,1,Apoi virus,Apodemus speciosus,J. S. Mackenzie and D. T. Williams,2009,"The zoonotic flaviviruses of southern, south-e...",Zoonoses Public Health,56.0,6-7,338-56,1903.0,MAMMALIA,RODENTIA,MURIDAE,Large Japanese Field Mouse,"(Temminck, 1844)",Micromys speciosus subspecies ainu,LC
4,4,Bagaza virus,Alectoris rufa,"D. Buitrago, A. Rocha, C. Tena-Tomas, M. Vigo,...",2012,Real-time fluorogenic reverse transcription po...,J Vet Diagn Invest,24.0,5,959-63,22678711.0,AVES,GALLIFORMES,Phasianidae,Red-legged Partridge,"(Linnaeus, 1758)",NaN,NT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
876,561,Zika virus,Callithrix jacchus,"C. Akoua-Koffi, K. D. Ekra, A. B. Kone, N. S. ...",2002,[Detection and management of the yellow fever ...,Med Trop (Mars),62.0,3,305-9,41518.0,MAMMALIA,PRIMATES,CALLITRICHIDAE,"Common Marmoset, White-tufted-ear Marmoset","(Linnaeus, 1758)",NaN,LC
877,565,Zika virus,Macaca mulatta,E. B. Hayes,2009,Zika virus outside Africa,Emerg Infect Dis,15.0,9,1347-50,12554.0,MAMMALIA,PRIMATES,CERCOPITHECIDAE,"Rhesus Monkey, Rhesus Macaque","(Zimmermann, 1780)",Macaca brachyurus |Macaca brevicaudatus |Mac...,LC
878,564,Zika virus,Macaca fascicularis,"G. H. Leung, R. W. Baird, J. Druce and N. M. A...",2015,Zika Virus Infection in Australia Following a ...,Southeast Asian J Trop Med Public Health,46.0,3,460-4,12551.0,MAMMALIA,PRIMATES,CERCOPITHECIDAE,"Nicobar Crab-eating Macaque, Nicobar Cynomolgu...","(Raffles, 1821)",NaN,LC
879,566,Zika virus,Pongo pygmaeus,"N. D. Wolfe, A. M. Kilbourn, W. B. Karesh, H. ...",2001,Sylvatic transmission of arboviruses among Bor...,American Journal of Tropical Medicine and Hygiene,64.0,5-6,310-316,17975.0,MAMMALIA,PRIMATES,HOMINIDAE,Bornean Orangutan,"(Linnaeus, 1760)",Simia pygmaeus,CR
880,567,Zika virus,Sapajus libidinosus,"S. Favoretto, D. Araujo, D. Oliveira, N. Duart...",2016,First detection of Zika virus in neotropical p...,bioRxiv,NaN,NaN,49395,136346.0,MAMMALIA,PRIMATES,CEBIDAE,"Bearded Capuchin, Black-striped Capuchin","(Spix, 1823)",Cebus libidinosus,LC

In [113]:
merged_df_left.shape

(566, 18)

In [94]:
#right merge
merged_df_right=pd.merge(df, metadata, on='Scientific Name', how='right')
merged_df_right

,sr no.,Virus,Scientific Name,Authors,Year,Title/accession number,Journal,Issue,Volume,Pages,Species ID,Class,Order,Family name,Common name,Authority,Synonyms,Red List status
0,522.0,West Nile virus,Struthio camelus,M. Venter and R. Swanepoel,2010,West Nile virus lineage 2 as a cause of zoonot...,Vector Borne Zoonotic Dis,10.0,7,659-64,45020636.0,AVES,STRUTHIONIFORMES,Struthionidae,Common Ostrich,"Linnaeus, 1758",NaN,LC
1,NaN,NaN,Struthio molybdophanes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22732795.0,AVES,STRUTHIONIFORMES,Struthionidae,Somali Ostrich,"Reichenow, 1883",NaN,VU
2,NaN,NaN,Rhea americana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22678073.0,AVES,STRUTHIONIFORMES,Rheidae,Greater Rhea,"(Linnaeus, 1758)",NaN,NT
3,NaN,NaN,Rhea pennata,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22678081.0,AVES,STRUTHIONIFORMES,Rheidae,Lesser Rhea,"d'Orbigny, 1834",NaN,LC
4,NaN,NaN,Nothocercus julius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22678157.0,AVES,STRUTHIONIFORMES,Tinamidae,Tawny-breasted Tinamou,"(Bonaparte, 1854)",NaN,LC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27500,NaN,NaN,Vicugna pacos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MAMMALIA,CETARTIODACTYLA,CAMELIDAE,NaN,NaN,NaN,NaN
27501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AVES,PASSERIFORMES,STURNIDAE,NaN,NaN,NaN,NaN
27502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MAMMALIA,RODENTIA,MURIDAE,NaN,NaN,NaN,NaN
27503,NaN,NaN,Sus scrofa domesticus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MAMMALIA,CETARTIODACTYLA,SUIDAE,NaN,NaN,NaN,NaN
27504,NaN,NaN,Hylomyscus pamfi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,972559.0,MAMMALIA,RODENTIA,MURIDAE,NaN,NaN,NaN,NaN

In [95]:
merged_df_right.shape

(27505, 18)

You should merge left as with the correction code, it is similar to 570, which is the correct number. It makes sense to merge left, because then you are merging onto the virus data, which should be the reference.

### Create a pivote table,
1. Rows are virueses  
2. Columns are Taxonomic orders  
3. Values are number of unique host species

In [121]:
merged_df_left.pivot_table(index='Virus', columns='Order', values='Scientific Name', aggfunc='nunique')

Order,ACCIPITRIFORMES,ANSERIFORMES,BUCEROTIFORMES,CAPRIMULGIFORMES,CARNIVORA,CATHARTIFORMES,CETARTIODACTYLA,CHARADRIIFORMES,CHIROPTERA,CICONIIFORMES,...,PERISSODACTYLA,PHOENICOPTERIFORMES,PICIFORMES,PILOSA,PRIMATES,PSITTACIFORMES,RODENTIA,STRIGIFORMES,STRUTHIONIFORMES,SULIFORMES
Virus,,,,,,,,,,,,,,,,,,,,,
Apoi virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
Bagaza virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Banzi virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN
Bouboui virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
Bussuquara virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN
Cacipacore virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dakar bat virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dengue virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,NaN,...,1.0,NaN,NaN,NaN,1.0,NaN,7.0,NaN,NaN,NaN
Entebbe bat virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Iguape virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ilheus virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
Japanese encephalitis virus,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,9.0,NaN,...,2.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
Koutango virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kunjin virus,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kyasanur forest virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,3.0,NaN,NaN,NaN
Louping-ill virus,NaN,NaN,NaN,NaN,1.0,NaN,7.0,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
Modoc virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN
Murray Valley encephalitis virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Omsk hemorrhagic fever virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN
Rio Bravo virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rocio virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
St. Louis Encephalitis virus,1.0,NaN,NaN,NaN,1.0,NaN,1.0,1.0,3.0,NaN,...,1.0,NaN,1.0,2.0,3.0,NaN,4.0,1.0,NaN,NaN
Tembusu virus,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tickborne encephalitis virus,1.0,7.0,NaN,NaN,1.0,NaN,8.0,2.0,NaN,NaN,...,NaN,NaN,2.0,NaN,1.0,NaN,13.0,NaN,NaN,NaN
Uganda S virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN
Usutu virus,4.0,NaN,1.0,1.0,NaN,NaN,1.0,3.0,1.0,1.0,...,2.0,NaN,2.0,NaN,NaN,NaN,1.0,9.0,NaN,NaN
Wesselsbron virus,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
West Nile virus,17.0,5.0,1.0,NaN,4.0,2.0,9.0,9.0,4.0,1.0,...,3.0,1.0,2.0,1.0,1.0,3.0,9.0,4.0,1.0,2.0
Yellow fever virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,9.0,NaN,2.0,NaN,NaN,NaN
Zika virus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN